### ISSUE TITLE
The performance on CIFAR-10 is inconsistent with the ICLR'23 paper FreeMatch

### ISSUE THREAD

**Issue by machengcheng2016** [GuanGui-nju/SCMatch#1]
Greetings!
I've been studying your excellent work recently.
However, I find in the [FreeMatch](https://openreview.net/pdf?id=PDrUPTXJI_A) paper that the performance of FlexMatch on CIFAR-10 (10 labels) is 86.15, but is only 66.07 in your paper. 
Since both of you utilize the TorchSSL framework, I wonder why the performances are inconsistent?

**Comment by GuanGui-nju** [comment]
Hello,
Thank you for your concern and for pointing out the problem. 
The accuracy rate fluctuated very much (50% to 80%) at 10labes in the experimental results I got at that time. 
Due to the inconsistency with other articles, I will check the code implementation once and redo the experiment in the near future and share my experimental results with you at that time. 
Thanks again for pointing it out!

**Comment by machengcheng2016** [comment]
Thanks a lot for your immediate reply! :smiley:
I think it is because of the random seed too, since Table 2 in your paper verifies that.
In fact, I spend two days on running [FixMatch](https://github.com/TorchSSL/TorchSSL/blob/main/config/fixmatch/fixmatch_cifar10_10_0.yaml) on my server twice, and get 73.56% and 75.32%, which are close to the reported performance in [FreeMatch](https://openreview.net/pdf?id=PDrUPTXJI_A) (75.21%).
I found nothing special in your cfg file and codes (removing `ctr_loss` can degenerate SCMatch into FixMatch), so I am a little confused. Maybe more tries can lead to fluctuant results? Looking forward to more results from you.
Btw, I didn't find the code of baseline method LESS, did you reimplement it by yourself?

**Comment by GuanGui-nju** [comment]
It was a pleasure to talk to you and it piqued my curiosity. 
The FixMatch code I run is based https://github.com/LeeDoYup/FixMatch-pytorch/tree/main.  And there is really no change in the parameter settings.
This also raises my question whether this is a discrepancy from the SSL library provided by FlexMatch (they appear to be the same). I'm happy to experiment further with this code, thank you.
